### ISSUE TITLE
Location of Header and Content Misplaced

### ISSUE THREAD

**Issue by TheChiefCoC** [nasal/newpiratebay#3]
I downloaded this theme but when i enable it , it has misplaced tables and the browse section is the same as oldpiratebay and blue colour : http://tpb.ifilescloud.com
Any fix for that?

**Comment by nasal** [comment]
You don't have bootstrap in the same location as me, apparently the folder name is random and changes every time, sorry!

Open _/views/layouts/head.php_ and change

&lt;link rel="stylesheet" href="/assets/603d1d82/css/bootstrap.min.css"&gt;

to

&lt;link rel="stylesheet" href="/assets/6229fccf/css/bootstrap.min.css"&gt;

It should work.

Will have to move this file to /css/.

**Comment by TheChiefCoC** [comment]
Will try and tell you @nasal 
EDIT: Great, Thanks a lot man , worked like a charm :+1: Closing issue
